/*
 * Copyright (C) 2012-2013 Netronome Systems, Inc.  All rights reserved.
 *
 * @file          blocks/vnic/pci_out_cfg.h
 * @brief         PCI.IN compile time configuration options
 */
#ifndef _BLOCKS__VNIC_PCI_OUT_CFG_H_
#define _BLOCKS__VNIC_PCI_OUT_CFG_H_

#define NFD_OUT_MAX_QUEUES              64

#define NFD_OUT_MAX_BATCH_SZ            4

#define NFD_OUT_BLM_POOL_START          BLM_NBI8_BLQ0_EMU_QID
#define NFD_OUT_BLM_RADDR               __LoadTimeConstant("__addr_emem1")
#define NFD_OUT_CREDITS_BASE            0

#define NFD_OUT_Q_EVENT_START           4
#define NFD_OUT_Q_START                 128
#define NFD_OUT_Q_EVENT_DATA            (3<<4)

/* Additional check queue constants */
#define NFD_OUT_MAX_RETRIES             5
#define NFD_OUT_FL_BATCH_SZ             8   /* Match configured watermark! */
/* #define NFD_OUT_PENDING_TEST     (NFD_OUT_BATCH_SZ - 1) */

#define NFD_OUT_STAGE_START_CTX         1
#define NFD_OUT_STAGE_WAIT_CYCLES       200
#define NFD_OUT_ISSUE_START_CTX         1


/* DMAConfigReg index allocations */
#define NFD_OUT_FL_CFG_REG              4
#define NFD_OUT_DESC_CFG_REG            8

#define NFD_OUT_DATA_CFG_REG            6
#define NFD_OUT_DATA_CFG_REG_SIG_ONLY   7

/* DMA defines */
#define NFD_OUT_FL_FETCH_MAX_IN_FLIGHT  16
#define NFD_OUT_DATA_MAX_IN_FLIGHT      64
#define NFD_OUT_DESC_MAX_IN_FLIGHT      32
#define NFD_OUT_FL_FETCH_DMA_QUEUE      NFP_PCIE_DMA_FROMPCI_HI
#define NFD_OUT_DATA_DMA_QUEUE          NFP_PCIE_DMA_TOPCI_LO
#define NFD_OUT_DESC_DMA_QUEUE          NFP_PCIE_DMA_TOPCI_MED
#define NFD_OUT_DATA_DMA_TOKEN          2

#define NFD_OUT_FL_CACHE_BUFS_PER_QUEUE 256
#define NFD_OUT_FL_CACHE_SOFT_THRESH    (NFD_OUT_FL_CACHE_BUFS_PER_QUEUE / 2)

/* XXX Check event type assignments for conflicts with autogenerated events */
#define NFD_OUT_FL_FETCH_EVENT_TYPE     13
#define NFD_OUT_DATA_EVENT_TYPE         14
#define NFD_OUT_DATA_IGN_EVENT_TYPE     7
#define NFD_OUT_DESC_EVENT_TYPE         9

#define NFD_OUT_FL_FETCH_EVENT_FILTER   11
#define NFD_OUT_DATA_EVENT_FILTER       12
#define NFD_OUT_DESC_EVENT_FILTER       13


/* Ring defines */
#define NFD_OUT_DESC_BATCH_RING_BAT     32
#define NFD_OUT_CPP_BATCH_RING_BAT      32
/* #define NFD_OUT_DATA_BATCH_RING_NUM  14  /\* XXX use generic resource allocation *\/ */


/* Debug defines */
#define NFD_OUT_DBG_CACHE_DESC_INTVL    1000000
#define NFD_OUT_DBG_ISSUE_DMA_INTVL     1000000

#endif /* !_BLOCKS__VNIC_PCI_OUT_CFG_H_ */
